#!/usr/bin/env ruby -w
# get weather for a range of times from environment canada, return as json

require 'open-uri'
require 'date'

# NOTE: You need to append "&Year=2009&Month=9&Day=15" to get a specific dmy, otherwise, you will get the current month
@datauri = "http://www.climate.weatheroffice.ec.gc.ca/climateData/bulkdata_e.html?timeframe=1&format=csv&type=hly&StationID=118" 

def tojson (from_date, to_date, station_id) 

  weather_in_csv = ""

  from_date.year.upto(to_date.year) {|this_year|

    if from_date.year == this_year then
      from_month = from_date.month
    else
      from_month = 1
    end

    if to_date.year == this_year then
      to_month = to_date.month
    else
      to_month = 12
    end

    from_month.upto(to_month) { |this_month|
      
      this_uri = @datauri + "&Year=%d&Month=%d&Day=%d" % [this_year, this_month, 0]
      
      # Grab weather and remove headers in CSV that we don't need.
      weather_in_csv << URI.parse(this_uri).read.gsub(/.*"Weather"\n(.*)/m, '\1')
    }
  }

  print weather_in_csv + "\n"
end

from = Date.new(y=2008, m=3, d=1)
to = Date.new(y=2009, m=4, d=20)

tojson(from, to, 118)
